version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: score2021@
      MYSQL_DATABASE: python_users_db
      MYSQL_USER: root
      MYSQL_PASSWORD: score2021@
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD}",
          "-e",
          "SELECT 1",
        ]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  data:
