# Generated by Django 5.0.2 on 2024-02-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='customusermodel',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
