name: CI-BI-PR
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obter código
        uses: actions/checkout@v4.1.7
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Passo 1 Build e Push 
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            felipelivre/djangopj:${{ github.run_number}}
            felipelivre/djangopj:latest
     




























      
